### ISSUE TITLE
Spaces disappear when links are in titles

### ISSUE THREAD

**Issue by alexfauquette** [konsalex/gatsby-wordpress-migrate#8]
## Description

When I have input like that : 

```<strong>To get useful code suggestions as you type, I recommend installing the&nbsp;</strong><a href="https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client"><strong>PHP Intelephense extension</strong></a><strong>&nbsp;for VS Code.</strong>```

the non-breaking space is removed. Precisely, I get

```**To get useful code suggestions as you type, I recommend installing the**[**PHP Intelephense extension**](http://the-url)**for VS Code.**```

**Comment by konsalex** [comment]
Hm I will check this out as soon as i will find time! That's strange to be honest!

What OS do you have @alexfauquette ?

**Comment by alexfauquette** [comment]
@konsalex I'm on Ubuntu 18.04.3 LTS

**Comment by konsalex** [comment]
Hey @alexfauquette . Try the 1.0.6 I think the error is fixed now.

Open the issue again if you face any difficulty ✌️
